spring:

  datasource:
    url: jdbc:h2:./db/logdb
    username: sa
    password: ''
    testWhileIdle: true
    validationQuery: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 50

logging:
  level:
    org.hibernate.SQL: info